name: CI/CD Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22.14"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install
          pnpm drizzle-kit push
        env:
          DB_FILE: ${{ secrets.DB_FILE }}

      - name: Build the project
        env:
          DB_FILE: ${{ secrets.DB_FILE }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: pnpm build

      - name: Archive production build
        run: tar -czf website.tar.gz .next public package.json pnpm-lock.yaml next.config.ts

      - name: Copy to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: website.tar.gz
          target: ~/deployments/phill030.de

      - name: Deploy to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deployments/phill030.de
            tar -xzf website.tar.gz
            rm website.tar.gz
            pnpm install -P
            screen -S website -X quit || true
            screen -dmS website bash -lc "pnpm start -p 1111"
